<?php

namespace InteractiveValley\VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetVentaRepository extends EntityRepository
{
}
