productos:
    resource: "@ProductosBundle/Controller/"
    type:     annotation
    prefix:   /

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

ventas:
    resource: "@VentasBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

#_liip_imagine:
#    resource: "@LiipImagineBundle/Resources/config/routing.xml"