security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/backend
            provider: usuarios
            form_login:
                login_path: backend_login
                check_path: backend_login_check
                remember_me: true
                use_referer: true
            logout:
                path: backend_logout
                target: backend_login
            security: true
            anonymous: true
        frontend:
            pattern:  ^/
            provider: usuarios
            form_login:
                check_path: login_check
                success_handler: richpolis.security.authentication_handler
                failure_handler: richpolis.security.authentication_handler
            oauth:
                resource_owners:
                    facebook:    "/login/check-facebook"
                    twitter:     "/login/check-twitter"
                login_path:     /login
                failure_path:   /login 
                oauth_user_provider:
                   #servicio para logear al usuario.
                    service: my_user_provider
            logout:
                path: logout
                target: login
            remember_me:
                key:        countdown1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
            security: true
            anonymous: true

    access_control:
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend, roles: [ROLE_ADMIN] }
        - { path: ^/inicio, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios, roles: [ROLE_USER] }

    encoders:
        InteractiveValley\BackendBundle\Entity\Usuario:        { algorithm: sha512, iterations: 10 }


    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: InteractiveValley\BackendBundle\Entity\Usuario, property: email }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]