<?php

namespace InteractiveValley\ProductosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApartadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartadoRepository extends EntityRepository
{
}
