<?php

namespace InteractiveValley\ProductosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT MAX(c.position) as value 
            FROM ProductosBundle:Categoria c 
            ORDER BY c.position ASC
        ');
        
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
    public function queryFindByActive(){
        $query= $this->getEntityManager()->createQueryBuilder();
        $query->select('c')
                ->from('InteractiveValley\ProductosBundle\Entity\Categoria', 'c')
                ->where('c.isActive=:activo')
                ->setParameter('activo', true)
                ->orderBy('c.position', 'ASC');
        return $query->getQuery();
    }
    
    public function findByActive(){
        $query= $this->queryFindByActive();
        return $query->getResult();
    }
    
}
