<?php

namespace InteractiveValley\ProductosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
            SELECT MAX(c.position) as value 
            FROM ProductosBundle:Categoria c 
            ORDER BY c.position ASC
        ');
        $max=$query->getResult();
        return $max[0]['value'];
    }
}
