<?php

namespace InteractiveValley\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository
{
    public function queryUsuariosResidencial($residencial){
        $query= $this->getEntityManager()->createQueryBuilder();
        $query->select('u')   
              ->from('InteractiveValley\BackendBundle\Entity\Usuario', 'u')
              ->orderBy('u.nombre', 'ASC');
        return $query->getQuery();
    }
	
	public function findUsuariosResidencial($residencial){
        $query = $this->queryUsuariosResidencial($residencial);
		return $query->getResult();
    }
}